tiangou/cart/urls.py
from django.urls import path
from cart import views
app_name='cart'
urlpatterns = [
    path('cart/', views.Cart),
    path('update/<int:gid>/', views.CartUpdateView.as_view()),
    path('update/', views.CartUpdateView1.as_view()),
    path('delete/<int:gid>/', views.CartDeleteView.as_view()),
    path('perinf/', views.perInf),
    path('paycart/',views.paycart),
    path('endpay/',views.endpay)
]

tiangou/tiangou/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from good import views as gviews
urlpatterns = [
    path('', gviews.index),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls',namespace='user')), #为用户模块分配名字空间
    path('good/', include('good.urls',namespace='good')), #为商品模块分配名字空间
    path('order/', include('order.urls',namespace='order')), #为订单模块分配名字空间
    path('cart/', include('cart.urls',namespace='cart')), #为订单模块分配名字空间

]

tiangou/user/urls.py
from django.conf.urls import url
from user import views
from django.contrib import admin
from django.urls import path
from user import views
app_name='user'
urlpatterns = [
    path('login/', views.Login,name='login'),
    path('register/',views.Register,name='register'),
    path('perInf/',views.perInf),
    path('logout/',views.Logout,name='logout'),
    path('order/<int:num>/',views.showorders),
    path('placeorder/<int:oid>/',views.placeorder),
    path('addsite_show/',views.addresschange,name='addsite_show')

]

tiangou/cart/models.py
from django.db import models

# Create your models here.
class cart(models.Model):
    cartId=models.IntegerField(db_column='c_id')#购物车ID
    userId=models.IntegerField(db_column='u_id')#购物车的主人的ID
    g_id=models.IntegerField(db_column='g_id')#商品的ID
    goodAmount=models.IntegerField(db_column='c_number')#购物车里该商品的数量
    class Meta:
        db_table='tb_buycar'

tiangou/cart/views.py
from collections import Set
from order.models import order

from django.db.models import QuerySet
from django.http import JsonResponse, request
from django.http.response import HttpResponse
from django.shortcuts import render, redirect
from good.views import detail
# Create your views here.
from django.views import View

from cart.models import cart
from good.models import good
from user.models import reciver, user

class newGood():#一个商品类，里面放着我需要得到的商品信息
    goodName=''#商品名
    goodUnite=''#商品单位
    goodPrice=0#商品单价
    goodUrl=''#商品图片地址
    goodId=0#商品ID
    goodAmount=0#商品数量
    goodTotalPrice=0#商品名
def Cart(request):#跳转到购物车界面
    global userid
    userid = request.session.get('u_id')
    carts = cart.objects.filter(userId=userid)#购物车set，里面放着所有本人的购物车信息
    goodSet = set()#新建一个表，这里有着购物车里的所有商品
    totalCount = 0
    totalPrice = 0
    for aCart in carts:
        totalCount += aCart.goodAmount
        aGood=newGood()
        TheGood=good.objects.filter(g_id=aCart.g_id).first()
        aGood.goodName = TheGood.g_name
        aGood.goodUnite = '件'
        aGood.goodPrice = TheGood.g_price
        aGood.goodUrl = TheGood.g_picture
        aGood.goodId = aCart.g_id
        aGood.goodAmount = aCart.goodAmount
        aGood.goodTotalPrice = aGood.goodPrice * aGood.goodAmount
        totalPrice += aGood.goodTotalPrice
        goodSet.add(aGood)
    return render(request, 'cart.html',{'total_count':totalCount, 'skus':goodSet, 'total_price':totalPrice})

class CartUpdateView(View):
    '''购物车记录更新'''
    def get(self, request,gid):
        # 接收数据
        sku_id = int(gid)
        count = request.GET.get('count')
        # 数据校验
        if not all([sku_id, count]):
            message='数据不完整'
            return detail(request,sku_id,msg=message)

        # 校验添加的商品数量
        try:
            count = int(count)
        except Exception as e:
            # 数目出错
            message='商品数目出错'
            return detail(request,sku_id,msg=message)

        # 校验商品是否存在
        try:
            sku = good.objects.get(g_id=sku_id)
        except cart.DoesNotExist:
            # 商品不存在
            message='商品不存在'
            return detail(request,sku_id,msg=message)

        # 校验商品的库存
        if count > sku.g_total:
            message='商品库存不足'
            return detail(request,sku_id,msg=message)

        #更新购物车表的内容

        if (cart.objects.filter(userId=int(request.session.get('u_id')),g_id=sku_id).exists()):

            newCart = cart.objects.get(userId=int(request.session.get('u_id')),g_id=sku_id)
            total_count=newCart.goodAmount+count
            cart.objects.filter(userId=int(request.session.get('u_id')),g_id=sku_id).update(goodAmount=total_count)
        else:
            cart.objects.create(userId=int(request.session.get('u_id')),g_id=sku_id,goodAmount=count)
        # 计算用户购物车中商品的总件数
        total_count = 0
        carts = cart.objects.filter(userId=int(request.session.get('u_id')))
        for aCart in carts:
            total_count += aCart.goodAmount
        # 返回应答
        message='加入购物车成功'
        return detail(request,sku_id,msg=message)


class CartUpdateView1(View):
    '''购物车记录更新'''
    def post(self, request):
        # 接收数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')
        # 数据校验
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})
        # 校验添加的商品数量
        try:
            count = int(count)
        except Exception as e:
            # 数目出错
            return JsonResponse({'res': 2, 'errmsg': '商品数目出错'})
        # 校验商品是否存在
        try:
            sku = good.objects.get(g_id=sku_id)
        except cart.DoesNotExist:
            # 商品不存在
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})
        # 校验商品的库存
        if count > sku.g_total:
            return JsonResponse({'res': 4, 'errmsg': '商品库存不足'})
        # 更新购物车表的内容
        userid = int(request.session.get('u_id'))
        cart.objects.filter(userId=userid, g_id=sku_id).update(goodAmount=count)
        # 计算用户购物车中商品的总件数 {'1':5, '2':3}
        total_count = 0
        vals = cart.objects.filter(userId=userid)
        for val in vals:
            total_count += val.goodAmount
        # 返回应答
        return JsonResponse({'res': 5, 'total_count': total_count, 'message': '更新成功'})

class CartDeleteView(View):
    '''购物车记录删除'''
    def get(self, request,gid):
        '''购物车记录删除'''
        # 接收参数
        sku_id = int(gid)
        # 业务处理:删除购物车记录
        # 计算用户购物车中商品的总件数 {'1':5, '2':3}
        total_count = 0
        userid=int(request.session.get('u_id'))
        result = cart.objects.filter(userId=int(request.session.get('u_id')), g_id=sku_id)
        result.delete()
        for i in range(len(result)):
            result[i].save()
        carts = cart.objects.filter(userId=userid)
        for aCart in carts:
            total_count += aCart.goodAmount

        # 返回应答
        return redirect('/cart/cart/')


def perInf(request):
    # 判断是否已经登录
    if request.session.get('islogin') == '1':
        # 从session获取用户id
        curr_u_id = int(request.session.get('u_id'))
        # 查询用户
        curr_user = user.objects.get(u_id=curr_u_id)
        return redirect('/cart/cart/')
    else:
        # 跳转至登录界面
        return redirect('/user/login/')
def paycart(request):
    data=request.GET
    userid = request.COOKIES.get('userid')
    # 通过获取前端get请求的参数，找到goods_id和对应的数量
    request_data=[]
    for key,value in data.items():
        if key.startswith('goods'):
            goods_id = key.split('_')[1]
            count = request.GET.get('count_'+goods_id)
            request_data.append((int(goods_id),int(count)))
    goodSet = set()
    show_data=[]
    total_price=0
    total_count=0
    for a in request_data:
        TheGood=good.objects.get(g_id=a[0])
        total_count+=a[1]
       
        
        aGood=newGood()
        
        aGood.goodName = TheGood.g_name
        aGood.goodUnite = '件'
        aGood.goodPrice = TheGood.g_price
        aGood.goodUrl = TheGood.g_picture
        aGood.goodId = TheGood.g_id
        aGood.goodAmount = a[1]
        aGood.goodTotalPrice = aGood.goodPrice * aGood.goodAmount
        total_price += aGood.goodTotalPrice
        goodSet.add(aGood)
        order.objects.create(u_id=int(request.session.get('u_id')),g_id=TheGood.g_id,o_number=a[1],price=aGood.goodTotalPrice,pay_status=-1)
        cart.objects.filter(userId=int(request.session.get('u_id')),g_id=TheGood.g_id).delete()
    if total_price>=50:
        transit_price=0
    else:
        transit_price=0
    total_pay=total_price-transit_price
    hasaddress=reciver.objects.filter(u_id=int(request.session.get('u_id'))).exists()
    if (hasaddress):
        curr_reciver=reciver.objects.get(u_id=int(request.session.get('u_id')))
    else:
        curr_reciver=None
    return render(request,'place_order1.html',{'list':goodSet,'total_count':total_count,'total_price':total_price,'transit_price':transit_price,'total_pay':total_pay,'hasaddress':hasaddress,'reciver':curr_reciver})
def endpay(request):
    uid=int(request.session.get('u_id'))
    orderlist=order.objects.filter(u_id=uid,pay_status=-1)
    hasgoods=1
    status=1
    if not (reciver.objects.filter(u_id=int(request.session.get('u_id')))).exists():
        order.objects.filter(u_id=uid,pay_status=-1).update(pay_status=0)
        msg='您没有默认地址'
        msg1='编辑地址'
        url='/user/addsite_show/'
        return render(request,'pay.html',{'msg':msg,'msg1':msg1,'url':url})
    for o in orderlist:
        currgood=good.objects.get(g_id=o.g_id)
        print(currgood.g_total)
        print(o.o_number)
        if currgood.g_status==0:
            status=0
        if currgood.g_total<o.o_number:
            hasgoods=0
    if hasgoods==0:
        order.objects.filter(u_id=uid,pay_status=-1).update(pay_status=0)
        msg='库存不足'
        msg1='返回首页'
        url='/'
        return render(request,'pay.html',{'msg':msg,'msg1':msg1,'url':url})
    if status==0:
        order.objects.filter(u_id=uid,pay_status=-1).update(pay_status=0)
        msg='商品已下架'
        msg1='返回首页'
        url='/'
        return render(request,'pay.html',{'msg':msg,'msg1':msg1,'url':url})
    order.objects.filter(u_id=uid,pay_status=-1).update(pay_status=1)


    msg='支付成功'
    msg1='返回首页'
    url='/'
    return render(request,'pay.html',{'msg':msg,'msg1':msg1,'url':url})

tiangou/templates/base.html
{# 首页 注册 登录 #}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load static %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {# 网页标题内容块 #}
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	{# 网页顶部引入文件块 #}
    {% block topfiles %}
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="/static/js/search.js"></script>
	{% endblock topfiles %}
</head>
<body>
{# 网页顶部欢迎信息块 #}
{% block header_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天狗商城!</div>
			<div class="fr">
                {% if islogin %}
				<div class="login_btn fl">
					欢迎您：<em>{{ username }}</em>
                    <span>|</span>
					<a href="/user/logout/" style='color:red' onclick="return check_return()">退出</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="/user/perInf/">用户中心</a>
					<span>|</span>
					<a href="/cart/cart/">我的购物车</a>
				</div>
			</div>
		</div>		
	</div>
{% endblock header_con %}

{# 网页顶部搜索框块 #}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="/" class="logo fl"><img src="{% static 'images/logo.jpg' %}"></a>
		<div class="search_con fl">
            <form method='post' action='/good/search/{{num}}/'> {%csrf_token%}
			<input type="text" class="input_text fl" name="search_good" placeholder="搜索商品" id='search'>
			<input type="submit" class="input_btn fr" name="submit" value="搜索" id='submit'>
		</form>
		</div>
		<div class="guest_cart fr">
			<a href="/cart/perinf" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div> {#未完成#}
		</div>
	</div>
{% endblock search_bar %}

{# 网站主体内容块 #}
{% block body %}{% endblock body %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2021 重庆天狗商城信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
    {# 网页底部html元素块 #}
    {% block bottom %}{% endblock bottom %}
    {# 网页底部引入文件块 #}
	{% block bottomfiles %}
	<script type="text/javascript">
	function check_return(){
		if (confirm('确定退出吗?')){
			return true
		}
		else{
			return false
		}
	}
	</script>
	{% endblock bottomfiles %}
</body>
</html>

tiangou/templates/base_detail_list.html
{# 详情页 列表页 #}
{% extends 'base.html' %}
{# 网站主体内容块 #}
{% block body %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
                    {% for type in types %}
					<li><a href="{% url 'goods:list' type.id 1 %}" class="{{ type.logo }}">{{ type.name }}</a></li>
					{% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="/">首页</a></li>
				
			</ul>
		</div>
	</div>
    {# 详情页，列表页主体内容块 #}
    {% block main_content %}{% endblock main_content %}
{% endblock body %}

tiangou/templates/detail.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天狗-商品详情</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	
	<script type="text/javascript" src="/static/js/search.js"></script>
</head>
<body>

	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天狗商城!</div>
			<div class="fr">
				  {% if islogin %}
				<div class="login_btn fl">
					欢迎您：<em>{{ username }}</em>
                   <span>|</span>
					<a href="/user/logout/" style='color:red' onclick="return check_return()">退出登录</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="/user/perInf/">用户中心</a>
					<span>|</span>
					<a href="/cart/cart/">我的购物车</a>
				</div>
			</div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href="/" class="logo fl"><img src="/static/images/logo.jpg"></a>
		<div class="search_con fl">
			<form method='post' action='/good/search/{{num}}/'> {%csrf_token%}
			<input type="text" class="input_text fl" name="search_good" placeholder="搜索商品" id='search'>
			<input type="submit" class="input_btn fr" name="submit" value="搜索" id='submit'>
            <input type="hidden" class="goodid fl" value="{{good.g_id}}">
		</form>
		</div>
		<div class="guest_cart fr">
			<a href="/cart/perinf" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">1</div>
		</div>
	</div>

	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
					<li><a href="/good/list/{{tid1}}/{{num}}/" class="fruit">电脑</a></li>
					<li><a href="/good/list/{{tid2}}/{{num}}/" class="seafood">手机</a></li>
					<li><a href="/good/list/{{tid3}}/{{num}}/" class="meet">男装</a></li>
					<li><a href="/good/list/{{tid4}}/{{num}}/" class="egg">女装</a></li>
					
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="/">首页</a></li>
				
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="/">全部分类</a>
		<span>></span>
		<a href="/good/list/{{good.t_id}}/{{num}}/">{{tname}}</a>
		<span>></span>
		<a href="">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src={{good.g_picture}} height='350', width='350'></div>

		<div class="goods_detail_list fr">
			<h3>{{good.g_name}}</h3>
			<br>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{good.g_price}}</em></span>
				<span class="show_unit">库  存：{{good.g_total}}</span>
			</div>
            <form name='frm' method='get'> {% csrf_token %}
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>

				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1" g_total={{good.g_total}} name='count'>
					<a href="javascript:;" class="add fr" g_total={{good.g_total}}>+</a>
					<a href="javascript:;" class="minus fr">-</a>	
				</div> 
			</div>
			<div class="total">总价：<em>{{good.g_price}}</em></div>
			
			<div class="operate_btn">
			{%if good.g_status%}
				<input type='button' class="buy_btn" value='立即购买' onclick='act1()'>
				<input type='button' class="add_cart" id="add_cart" value='加入购物车' onclick='act2()'>	
			{%else%}		
			    <input type='button' class="buy_btn" value='已下架' >
				<input type='button' class="add_cart" id="{{good.g_id}}" value='加入购物车' onclick='act2()'>
			{%endif%}
			    
			    
			</div>
			<br>
			<p style='font-size:17px;color:red;'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{msg}}</p>
            </form>

		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
				{%for ngood in newgoods %}
					<li>
						<a href="/good/detail/{{ngood.g_id}}/"><img src={{ngood.g_picture}}></a>
						<h4><a href="/good/detail/{{ngood.g_id}}/">{{ngood.g_name}}</a></h4>
						<div class="prize">￥{{ngood.g_price}}</div>
					</li>
				{%endfor%}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{good.g_intro}} </dd>
				</dl>
			</div>

		</div>
	</div>

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	<div class="add_jump"></div>

	<script type="text/javascript" src='/static/js/jquery-1.12.4.min.js'></script>
	<script type="text/javascript">

        // 计算商品的总价格
        function update_goods_amount() {
            // 获取商品的单价和数量
            price = $('.show_pirze').children('em').text()
            count = $('.num_show').val()
            // 计算商品的总价
            price = parseFloat(price)
            count = parseInt(count)
            amount = price*count
            // 设置商品的总价
            $('.total').children('em').text(amount.toFixed(2)+'元')
        }

        // 增加商品的数量
        $(document).on('click','.add',function () {
            //商品库存
            gtotal = $(this).attr("g_total")
            // 获取商品原有的数目
            count = $('.num_show').val()
            // 加1
            count = parseInt(count)+1
            if (count > gtotal){
                count = gtotal
            }
            // 重新设置商品的数目
            $('.num_show').val(count)
            // 更新商品的总价
            update_goods_amount()
        })

        // 减少商品的数量
        $(document).on('click','.minus',function () {
            // 获取商品原有的数目
            count = $('.num_show').val()
            // 减1
            count = parseInt(count)-1
            if (count <= 0){
                count = 1
            }
            // 重新设置商品的数目
            $('.num_show').val(count)
            // 更新商品的总价
            update_goods_amount()
        })

        // 手动输入商品的数量
        $('.num_show').blur(function () {
            //商品库存
            gtotal = $(this).attr("g_total")
            // 获取用户输入的数目
            count = $(this).val()
            // 校验count是否合法
            if (isNaN(count) || count.trim().length==0 || parseInt(count) <=0){
                count = 1
            }
            if (parseInt(count) > gtotal){
                count = gtotal
            }
            // 重新设置商品的数目
            $(this).val(parseInt(count))
            // 更新商品的总价
            update_goods_amount()
        })

        // 获取add_cart div元素左上角的坐标
		var $add_x = $('#add_cart').offset().top;
		var $add_y = $('#add_cart').offset().left;

        // 获取show_count div元素左上角的坐标
		var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;


		$(document).on('click','#add_cart',function(){
            // 获取商品id和商品数量
            sku_id = $(this).attr('sku_id') // attr prop
            count = $('.num_show').val()
            csrf = $('input[name="csrfmiddlewaretoken"]').val()
            // 组织参数
            params = {'g_id':sku_id, 'count':count, 'csrfmiddlewaretoken':csrf}
            // 发起ajax post请求，访问/cart/add, 传递参数:sku_id count
            $.post('/cart/add', params, function (data) {
                if (data.res == 5){
                    // 添加成功
                    $(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
                    $(".add_jump").stop().animate({
                        'left': $to_y+7,
                        'top': $to_x+7},
                        "fast", function() {
                            $(".add_jump").fadeOut('fast',function(){
                                // 重新设置用户购物车中商品的条目数
                                $('#show_count').html(data.total_count);
                            });
			        });
                }
                else{
                    // 添加失败
                    alert(data.errmsg)
                }
            })
		})

        $(document).on('click',".buy_btn",function(){
            sku_id = $(this).attr('sku_id')
            count = $('.num_show').val()
            csrf = $('input[name="csrfmiddlewaretoken"]').val()
            // 组织参数
            params = {'g_id':sku_id, 'count':count, 'csrfmiddlewaretoken':csrf}
            $.post('#', params , function(data){    //填入创建订单函数的url
                if(data.res!=5){    //添加失败
                    alert(data.errmsg)
                }
            })
        })
	</script>
	<script type="text/javascript">
	function check_return(){
		if (confirm('确定退出吗?')){
			return true
		}
		else{
			return false
		}
	}
	</script>
    <script type="text/javascript">
    function act1(){
        document.frm.action='/order/placeorder/{{good.g_id}}/'
        document.frm.submit()
    }
    function act2(){
        document.frm.action='/cart/update/{{good.g_id}}/'
        document.frm.submit()
    }
	
    </script>
</body>
</html>

tiangou/templates/user_center_site.html
{% extends 'base_user_center.html' %}
{% block topfiles %}
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="/static/js/user_center.js"></script>
{% endblock topfiles %}

{% block right_content %}
	
        <div class="right_content clearfix">
		<h2 class="common_title2">收货地址管理</h2>
		<div class="site_con">
		<dl>
		<dt>默认地址：</dt>
		{% if hasaddress %}
			<dd>({{reciver.r_province}}省) ({{reciver.r_city}}市)({{reciver.r_district}}区)({{reciver.r_address}})({{reciver.r_name}} 收){{ reciver.r_phone }}</dd>
		{% else %}
			<dd>无默认地址</dd>
		{% endif %}
				</dl>				
				</div>
				<h3 class="common_title2">地址管理</h3>
				<div class="site_con">
					<form method="post" action={%url 'user:addsite_show' %}>
						{% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="r_name">
						</div>
						<div class="form_group">
							<label>邮&emsp;编：</label>
							<input type="text" name="r_zipcode">
						</div>
						<div class="form_group">
							<label>手&emsp;机：</label>
							<input type="text" name="r_phone">
						</div>

						<div class="form_group form_group2">
							<label>地&emsp;址：</label>
							<div><input type="text" name="r_province"><font size="2">省</font></div>
							<div><label>&emsp;&emsp;&emsp;</label><input type="text" name="r_city" align="right"/><font size="2">市</font></div>
							<div><label>&emsp;&emsp;&emsp;</label><input type="text" name="r_district"><font size="2" >区/县</font></div>
							
                   			<div><label>具体地址:</label>
                    		<input type="text" name="r_address"></div></div>
							<input type="submit" name="" value="保存" class="info_submit">
                            </form>
							<br>
							<br>
							<br>
					<p style='color:red;text-align:center;font-size:17px' >{{errmsg}}<p>
{% endblock right_content %}